### ISSUE TITLE
ADHD-200

### ISSUE THREAD

**Issue by zihao2018023** [ChristopherSims/FMRI_ADHD_Classification#1]
Hello, I would like to ask what kind of preprocessing has been done to the.nii file with the prefix sfnwmrda in your code? Why the.NII file in the ADHA-200 data set I downloaded does not have the prefix sfnwmrda, please kindly advise.

**Comment by ChristopherSims** [comment]
it is listed on the ADHD-200 website. this prefix is the aberration-corrected dataset. You can use whatever dataset you want to.
